updateFrequency: 5m
projects:
  - type: shell
    repository: git@github.com:paullaffitte/gravity.git
    branch: master
    options:
      script: ls && cat README.md | head -n 1
  - name: gravity-bis
    type: shell
    repository: git@github.com:paullaffitte/gravity.git
    branch: master
    options:
      script: ls
