version: '3.8'

services:
  generic-gitops:
    build: .
    environment:
      - SSH_AUTH_SOCK=${SSH_AUTH_SOCK}
      - SSH_KNOWN_HOSTS=/root/.ssh/known_hosts
    volumes:
      - ${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}
      - $HOME/.ssh/known_hosts:/root/.ssh/known_hosts
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.yaml:/etc/generic-gitops/config.yaml
      - ./configs:/etc/generic-gitops/configs
      - /var/lib/generic-gitops/repositories:/var/lib/generic-gitops/repositories
