#!/usr/bin/env python3

import os
import argparse

parser = argparse.ArgumentParser(description='Execute an arbitrary script')

parser.add_argument('--script', help='Script to run', required=True)

args = parser.parse_args()

print('>', args.script, flush=True)
os.system(args.script)
