#!/usr/bin/env python3

import argparse
from utils import run

parser = argparse.ArgumentParser()
parser.add_argument('--env-file', help='.env to use')
args = parser.parse_args()

command = 'docker compose'

if args.env_file:
  command += f' --env-file {args.env_file}'

command += ' up -d --build --remove-orphans'

run(command.split(' '))
