#!/usr/bin/env python3

import sys
import json

from utils import run


opts = json.load(sys.stdin)

command = "docker compose"

if opts.get("env-file"):
    command += f" --env-file {opts['env-file']}"

command += " up -d"

if opts.get("build") is True:
    command += " --build"

if opts.get("remove-orphans", True) is True:
    command += " --remove-orphans"

run(command.split(" "))
