#!/usr/bin/env python3

import argparse
from utils import run

parser = argparse.ArgumentParser(description='Execute an arbitrary script')

parser.add_argument('--script', help='Script to run', required=True)

args = parser.parse_args()

run(['sh', '-c', args.script])
